### ISSUE TITLE
Question about using SWAD

### ISSUE THREAD

**Issue by DHdroid** [yaoxufeng/PCL-Proxy-based-Contrastive-Learning-for-Domain-Generalization#1]
Hello, I have a question about the results of PACS!

When I ran your code with the same command in `run.sh`, the final result was like below:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/43927732/181702562-1b093ffe-50d0-4f85-bc7c-aa40f6d11b62.png">

From the table above, It seems that the performance in the paper cannot be achieved without SWAD. So my question is: Is SWAD needed to reproduce results in the paper? Or do I have to adjust HPs further?

Thank you for your time and consideration :)

**Comment by yaoxufeng** [comment]
Thanks for interesting in our work. Our repo is built on SWAD and the result is achieved with SWAD. 
It's also interesting to try our approach without SWAD.

**Comment by DHdroid** [comment]
Thanks for your kind reply :)
