### ISSUE TITLE
Question about results

### ISSUE THREAD

**Issue by Cassiatora** [yaoxufeng/PCL-Proxy-based-Contrastive-Learning-for-Domain-Generalization#3]
Hi, I am very interested in your work. But there is some gap between my reproduced results and those in the paper. Maybe because of the torch version? this is the log.txt. 
[log.txt](https://github.com/yaoxufeng/PCL-Proxy-based-Contrastive-Learning-for-Domain-Generalization/files/9256232/log.txt)
![image](https://user-images.githubusercontent.com/58909848/182750177-f30ccf8d-bd54-45e2-8335-29d2fb8ee04d.png)

**Comment by yaoxufeng** [comment]
Hi Cassiatora,
Thanks for your interest in our work! I checked your log.txt and found there may exist some error in your dataset.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/15065134/182758378-774b111e-84e2-4db5-a171-b3de60e3dcbf.png">

Following is my log:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/15065134/182758420-d38b2056-1ca6-4523-8b89-bc3eb6c62e32.png">

**Comment by Cassiatora** [comment]
Thank you for your reply. I will check the dataset.
