### ISSUE TITLE
how to set the parameters

### ISSUE THREAD

**Issue by Cassiatora** [yaoxufeng/PCL-Proxy-based-Contrastive-Learning-for-Domain-Generalization#5]
Hi, I want to run the algorithms with datasets of another task. But the results are not good with the same parameters as PACS. Could you please share some experience with setting the parameters? This is the log. Thank you.
[log.txt](https://github.com/yaoxufeng/PCL-Proxy-based-Contrastive-Learning-for-Domain-Generalization/files/9288063/log.txt)

 
![image](https://user-images.githubusercontent.com/58909848/183588385-e807033e-c272-408b-83bb-cc296bff7e67.png)

**Comment by yaoxufeng** [comment]
Hi Cassiatora,

Thanks again for your interest in our work.
You can try different scale factor, hidden-size of the encoder and learning rate schedule for encoder and fea_proj.

**Comment by Cassiatora** [comment]
> Hi Cassiatora,
> 
> Thanks again for your interest in our work. You can try different scale factor, hidden-size of the encoder and learning rate schedule for encoder and fea_proj.

Thanks for your quick reply. I don't know the specific meaning of  tr_outloss、env0_out、env1_in. Would you mind telling me? Thank you for your patience in replying！

**Comment by luffy-lxd** [comment]
> Hi Cassiatora,
> 
> Thanks again for your interest in our work. You can try different scale factor, hidden-size of the encoder and learning rate schedule for encoder and fea_proj.

hi，could you please share your parameters of TerraIncognita datastet?   i have tried many times ,but the results are not good with the same parameters as TerraIncognita.  thanks a lot!
